### ISSUE TITLE
Add --run-whisper-locally option

### ISSUE THREAD

**Issue by platisd** [platisd/skonaki#1]
Add the option to run `whisper` locally with a `--run-whisper-locally` option.

- Create a new `requirements-local-whisper.txt` which would include all dependencies + [whisper](https://pypi.org/project/openai-whisper/) or [stable-ts](https://pypi.org/project/stable-ts/)
- Add `--run-whisper-locally` optional argument
- Only import `whisper` if the user has selected to run the model locally
  - If the library cannot be imported tell the user to install the correct dependencies from ``requirements-local-whisper.txt``
- Get the transcript from the local run of `whisper`
  - Make sure you disable the word-highlighting
- Continue with the rest of the pipeline as it was before

**Comment by Marble879** [comment]
Hi, is it possible to work on this? I am very interested to give it a try 😊

**Comment by platisd** [comment]
It's up for grabs, go for it! :+1:
